# Generated by Django 4.1 on 2022-09-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageFileter',
            new_name='ImageFilter',
        ),
    ]
